version: '2'
services:

  sec-fw-mysql:
    build: backend-bbdd/.
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=secframework

  sec-fw-frontend:
    build: frontend/.
    ports:
      - 5000:5000
    environment: 
      - FLASK_APP=app/app.py
      - FLASK_ENV=development
      - SQL_SERVER=sec-fw-mysql

  
  